In [2]:
import pandas as pd

# THIS IS USED FOR DATA PREPARATON

In [4]:
data = pd.read_csv('IRIS[1].csv')
print(data)

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]


In [7]:
selected_columns = data[['sepal_length', 'sepal_width']]
print(selected_columns)

     sepal_length  sepal_width
0             5.1          3.5
1             4.9          3.0
2             4.7          3.2
3             4.6          3.1
4             5.0          3.6
..            ...          ...
145           6.7          3.0
146           6.3          2.5
147           6.5          3.0
148           6.2          3.4
149           5.9          3.0

[150 rows x 2 columns]


In [5]:
filtered_data=data[data['sepal_length']>5]
print(filtered_data)

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
5             5.4          3.9           1.7          0.4     Iris-setosa
10            5.4          3.7           1.5          0.2     Iris-setosa
14            5.8          4.0           1.2          0.2     Iris-setosa
15            5.7          4.4           1.5          0.4     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[118 rows x 5 columns]


In [12]:
grouped_data = data.groupby('species').sum()
print(grouped_data)

                 sepal_length  sepal_width  petal_length  petal_width
species                                                              
Iris-setosa             250.3        170.9          73.2         12.2
Iris-versicolor         296.8        138.5         213.0         66.3
Iris-virginica          329.4        148.7         277.6        101.3


# merging two columns

In [14]:
data1 = pd.read_csv('IRIS[1].csv')
data2 = pd.read_csv('IRIS[1].csv')

In [16]:
merged_data=pd.merge(data1,data2, on='sepal_length')
print(merged_data)


     sepal_length  sepal_width_x  petal_length_x  petal_width_x  \
0             5.1            3.5             1.4            0.2   
1             5.1            3.5             1.4            0.2   
2             5.1            3.5             1.4            0.2   
3             5.1            3.5             1.4            0.2   
4             5.1            3.5             1.4            0.2   
..            ...            ...             ...            ...   
895           7.7            3.0             6.1            2.3   
896           7.7            3.0             6.1            2.3   
897           7.7            3.0             6.1            2.3   
898           7.4            2.8             6.1            1.9   
899           7.9            3.8             6.4            2.0   

          species_x  sepal_width_y  petal_length_y  petal_width_y  \
0       Iris-setosa            3.5             1.4            0.2   
1       Iris-setosa            3.5             1.4       

# checking for null value   used for data cleaning
data.info() # column name has null value or not

In [17]:
data.fillna(0,inplace=True)
print(data)
# jah par null value hogi wah par 0 fill kar dega [fillna use]

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]


#  adding new column

In [19]:
def process_value(value):
    #apply custom logic to process each value
    processed_value = value*2
    return processed_value
data['processed_column']= data['sepal_length'].apply(process_value)
print(data)

     sepal_length  sepal_width  petal_length  petal_width         species  \
0             5.1          3.5           1.4          0.2     Iris-setosa   
1             4.9          3.0           1.4          0.2     Iris-setosa   
2             4.7          3.2           1.3          0.2     Iris-setosa   
3             4.6          3.1           1.5          0.2     Iris-setosa   
4             5.0          3.6           1.4          0.2     Iris-setosa   
..            ...          ...           ...          ...             ...   
145           6.7          3.0           5.2          2.3  Iris-virginica   
146           6.3          2.5           5.0          1.9  Iris-virginica   
147           6.5          3.0           5.2          2.0  Iris-virginica   
148           6.2          3.4           5.4          2.3  Iris-virginica   
149           5.9          3.0           5.1          1.8  Iris-virginica   

     processed_column  
0                10.2  
1                 9.8  
2  

# pivot is used here for data visualization

In [21]:
pivot_table = pd.pivot_table(data, values ='sepal_length', index='petal_length', columns='species')
print(pivot_table)

species       Iris-setosa  Iris-versicolor  Iris-virginica
petal_length                                              
1.0              4.600000              NaN             NaN
1.1              4.300000              NaN             NaN
1.2              5.400000              NaN             NaN
1.3              4.842857              NaN             NaN
1.4              4.916667              NaN             NaN
1.5              5.128571              NaN             NaN
1.6              4.914286              NaN             NaN
1.7              5.400000              NaN             NaN
1.9              4.950000              NaN             NaN
3.0                   NaN         5.100000             NaN
3.3                   NaN         4.950000             NaN
3.5                   NaN         5.350000             NaN
3.6                   NaN         5.600000             NaN
3.7                   NaN         5.500000             NaN
3.8                   NaN         5.500000             N

In [ ]:
# analytic real date and time

In [3]:
date['date_column'] = pd.to_datetime(data['sepal_length'])
data.set_index('date_column', inplace=True)
resampled_data = data.resample('M').sum()
print(resampled_data)

NameError: name 'data' is not defined

# 2. numpy

In [1]:
import numpy as np


In [2]:
#create a 1-d array
arr=np.array([1,2,3,4,5])
print(arr)
print("Sum:",np.sum(arr))
print("Mean:",np.mean(arr))
print("Max:",np.max(arr))
print("Min:",np.min(arr))

[1 2 3 4 5]
Sum: 15
Mean: 3.0
Max: 5
Min: 1


In [3]:
#reshape array to a 2X3 matrix
arr1= np.array([1,2,3,4,5,6])
reshaped_arr = arr1.reshape(2,3)
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


In [4]:
arr2 = np.random.random((3,3))
print(arr2)

[[0.99713417 0.80072424 0.93677806]
 [0.09779458 0.15384202 0.82508274]
 [0.80541167 0.80678872 0.42581183]]


In [5]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
result = arr1 + arr2
print(result)

[5 7 9]


In [7]:
#create a 2D array
arr3 = np.array([1,2,3])
arr4 = np.array([4,5,6])
print(arr3 + arr4)

[5 7 9]


In [15]:
#sum along row(axis=0)
data=np.array([[1,2],[3,4],[5,6]])
print(data)
sum_along_rows = np.sum(data,axis=0)
sum_along_columns = np.sum(data,axis=1)
print(sum_along_rows)
print(sum_along_columns)

[[1 2]
 [3 4]
 [5 6]]
[ 9 12]
[ 3  7 11]


In [16]:
arr6 =np.array([1,2,3,4,5,6])
#indexing
print(arr6[1]) # access element at index 1

# boolean masking
mask = data>2
filtered_data = data[mask]
print(filtered_data)

2
[3 4 5 6]


In [19]:
data = np.array([1,2,2,3,3,4,4,4,4,4,5,6,6,6,6,6,])

# unique elements
unique_elements = np.unique(data)

#count occurrence of unique elements 
element_counts=np.bincount(data)
print(unique_elements)
print(element_counts)

[1 2 3 4 5 6]
[0 1 2 2 5 1 5]


In [20]:
# simulated data for linear regression
x = np.array([1,2,3,4,5])
y = np.array([2,4,5,4,5])

#perform linear regression using numpy's polyfit
coefficients = np.polyfit(x,y,1)

#Extract slope and intercept from the coefficients
slope, intercept = coefficients
print("slope:",slope)
print("intercept:",intercept)

slope: 0.6000000000000002
intercept: 2.1999999999999993
